services:
  gateway:
    build:
      context: .
      dockerfile: ./gateway/Dockerfile
    ports:
      - "${GATEWAY_PORT}:80"
    environment:
      GIN_MODE: release
      auth_service_addr: auth:80
      products_service_addr: products:80
      client_service_addr: client:80
    restart: always
    networks:
      - public-network
      - private-network
    depends_on:
      postgres:
        condition: service_healthy
  client:
    build:
      context: .
      dockerfile: ./client/Dockerfile
    environment:
      DATABASE_URL: ${DATABASE_URL}
    restart: always
    networks:
      - private-network
    depends_on:
      postgres:
        condition: service_healthy
  auth:
    build:
      context: .
      dockerfile: ./auth/Dockerfile
    environment:
      DATABASE_URL: ${DATABASE_URL}
      JWT_SECRET_KEY: ${JWT_SECRET_KEY}
    restart: always
    networks:
      - private-network
    depends_on:
      postgres:
        condition: service_healthy

  products:
    build:
      context: .
      dockerfile: ./products/Dockerfile
    environment:
      DATABASE_URL: ${DATABASE_URL}
    restart: always
    networks:
      - private-network
    depends_on:
      postgres:
        condition: service_healthy
  postgres:
    image: postgres:15.3-alpine
    container_name: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: postgres
      POSTGRES_DB: orders
    ports:
      - "5432:5432"
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    networks:
      - public-network
      - private-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

networks:
  public-network:
    driver: bridge
  private-network:
    driver: bridge
    internal: true
