version: "3.8"
services:
  postgres:
    image: postgres:15.3-alpine
    container_name: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: postgres
      POSTGRES_DB: orders
    ports:
      - 5432:5432
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
