// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: users.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const inserUser = `-- name: InserUser :one
INSERT INTO users 
  ("name", "email", "password", "created_at", "updated_at") VALUES
  ( $1, $2, $3, now(), now() )
RETURNING "id"
`

type InserUserParams struct {
	Name     pgtype.Text
	Email    pgtype.Text
	Password pgtype.Text
}

func (q *Queries) InserUser(ctx context.Context, arg InserUserParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, inserUser, arg.Name, arg.Email, arg.Password)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}
